apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx
    spec:
#      tolerations:
#      - key: "hardware"
#        operator: "Equal"
#        value: "low"
#        effect: "NoExecute"
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

