apiVersion: v1
kind: Service
metadata:
  namespace: grafana
  labels:
    app: loki-grafana-nodeport
  name: loki-grafana-nodeport
spec:
  ports:
  - name: "80"
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: grafana
  type: NodePort
