apiVersion: v1
kind: Service
metadata:
  name: proxy-node
spec:
  ports:
  - name: proxy-node
    nodePort: 30880
    port: 8880
    targetPort: 80
    protocol: TCP
  selector:
    run: nginx2
  type: NodePort
