apiVersion: v1
kind: Service
metadata:
  name: moodle-app-svc
spec:
  selector:
    app: moodle-app
  ports:
    - port: {{ .Values.moodle.service.port }}
      targetPort: 8080
      nodePort: {{ .Values.moodle.nodePort }}
  type: {{ .Values.moodle.service.type }}	  