apiVersion: v1
kind: Service
metadata:
  name: moodle-db-svc
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: {{ .Values.mariadb.port }}
      targetPort: {{ .Values.mariadb.port }}
  type: {{ .Values.mariadb.service.type }}