apiVersion: v1
kind: Pod
metadata:
  name: writer
spec:
  containers:
  - image: busybox
    name: writer
    args:
    - sleep
    - "3600"
    volumeMounts:
    - mountPath: /data
      name: data-dir
  volumes:
  - name: data-dir
    persistentVolumeClaim:
      claimName: dynamic-pvc-data
