apiVersion: v1
kind: Service
metadata:
  name: moodle-app-svc
spec:
  selector:
    app: moodle-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080  # Porta exposta no Node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moodle-app
  template:
    metadata:
      labels:
        app: moodle-app
    spec:
      containers:
        - name: moodle
          image: bitnami/moodle:5.0
          env:
            - name: MOODLE_DATABASE_TYPE
              value: "mariadb"
            - name: MOODLE_DATABASE_HOST
              value: "moodle-db-svc"
              # tem que ser nome do Service (sc) do mariadb
            - name: MOODLE_DATABASE_PORT_NUMBER
              value: "3306"
            - name: MOODLE_DATABASE_NAME
              value: "moodle"
            - name: MOODLE_DATABASE_USER
              value: "moodleuser"
            - name: MOODLE_DATABASE_PASSWORD
              value: "moodlepass"
          ports:
            - containerPort: 8080
#          volumeMounts:
#            - name: data-dir
#              mountPath: /bitnami/moodle
#      volumes:
#        - name: data-dir
#          persistentVolumeClaim:
#            claimName: moodle-app-pvc
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: moodle-app-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: moodle-app-pv
  labels:
    app: moodle-app
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Mi
  local:
    path: /pods/moodle/app
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - s2-node-1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: moodle-app-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-app-pvc
spec:
  storageClassName: moodle-app-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      use: moodle-app
  volumeName: "moodle-app-pv"
